"""A synthetic stage, manifest and bundle, built the way `plan` and `pack`
build the real ones.

Everything here is invented: the passphrase is a test vector, the `.env` it
stages holds made-up values, and no path touches the operator's own tree. The
repo is public and a fixture that carried a real secret would be one commit
away from being one.
"""

import io
import json
import os
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

import novabundle as nb  # noqa: E402

HERE = pathlib.Path(__file__).resolve().parent
BACKUP_DIR = HERE.parent
FIXTURES = BACKUP_DIR / "fixtures"

# Synthetic. Not a passphrase anything real is sealed with.
PASSPHRASE = "aaaa-bbbb-cccc-dddd-eeee-ffff-gggg-hhhh"
OTHER_PASSPHRASE = "zzzz-yyyy-xxxx-wwww-vvvv-uuuu-tttt-ssss"

STAMP = "20260921T143002Z"

BASE = {
    "created_at": STAMP,
    "mode": "routine",
    "transport": "local",
    "source": {
        "host": "test-host",
        "os": "Linux 6.18.0-test",
        "repo_sha": "12ea01bf" + "0" * 32,
        "repo_dirty": False,
        "project": "nova",
        "compose_files": ["/repo/deploy/docker-compose.yml"],
        "profiles": ["inference"],
        "docker_version": "29.6.1",
        "compose_version": "v5.3.0",
        "pack_image_id": "sha256:" + "a" * 64,
    },
    "postgres": {
        "server_version": "16.10",
        "server_version_num": 160010,
        "pg_dump_version": "16.10",
        "pg_dump_major": 16,
        "container_image": "postgres:16",
        "container_image_id": "sha256:" + "b" * 64,
    },
    "session": {
        "TimeZone": "UTC",
        "DateStyle": "ISO, MDY",
        "IntervalStyle": "postgres",
        "extra_float_digits": "0",
        "bytea_output": "hex",
        "lc_numeric": "C",
    },
    "databases": [
        {
            "name": "nova_core",
            "owner": "core",
            "dump_member": "db/nova_core.dump",
            "dump_bytes": 0,
            "dump_sha256": "0" * 64,
            "counts_member": "db/nova_core.counts.tsv",
            "migrations_member": "db/nova_core.migrations.tsv",
            "tables": 2,
            "rows": 3,
            "selftest": {
                "scratch_db": "nova_selftest_a1b2c3d4",
                "tables_compared": 2,
                "equal": True,
            },
        }
    ],
    "identity": {
        "core_signing_key_sha256": "77d1" + "0" * 60,
        "tailnet_dns_name": None,
        "tailnet_state_carried": False,
        "device_count": 0,
        "people_count": 1,
    },
    "passphrase_source": "file",
    "excluded": [
        {
            "kind": "identity",
            "name": "core_signing_key",
            "disposition": "exclude-derived",
            "reason": "no device has ever paired on this hub, so there is no key to carry.",
        }
    ],
}


def entries():
    """What coverage() would hand `plan` for this synthetic stack."""
    return [
        nb.Entry(
            kind="volume",
            name="v4_memdata",
            disposition="include",
            reason="the notes",
            full_name="nova_v4_memdata",
            source="raw",
        ),
        nb.Entry(
            kind="volume",
            name="v4_ollama",
            disposition="exclude-redownload",
            reason="model weights, tens of GB, re-pulled on first use.",
            full_name="nova_v4_ollama",
            source="raw",
        ),
        nb.Entry(
            kind="bind",
            name="/repo/data",
            disposition="exclude-derived",
            reason="regenerated by detect_hardware on every install.",
            service="gateway",
            target="/data",
            source="config",
        ),
    ]


def write(path, text, mode=0o644):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    os.chmod(path, mode)


def make_stage(root: pathlib.Path) -> pathlib.Path:
    """The tree `backup.sh` would have staged by §9.1 step 13."""
    stage = root / "stage"
    inner = stage / "inner"
    (stage / "facts").mkdir(parents=True, exist_ok=True)

    write(inner / "db" / "nova_core.dump", "PGDMP" + "x" * 512)
    write(inner / "db" / "nova_core.counts.tsv", "public.people\t1\t42\npublic.turns\t2\t77\n")
    write(inner / "db" / "nova_core.migrations.tsv", "001_init.sql\t" + "c" * 64 + "\n")

    volume = inner / "volumes" / "v4_memdata"
    write(volume / "people" / "example" / "a-note.md", "a note\n")
    write(volume / "people" / "example" / "topics" / "a-topic.md", "another note\n")
    (volume / "empty-dir").mkdir(parents=True, exist_ok=True)
    link = volume / "people" / "current"
    if not link.exists():
        link.symlink_to("example")

    # THE SHAPES REAL DATA HAS, and the reason this fixture is not built with
    # one umask and left alone. A markdown memory volume carries
    # group-writable notes and group-writable directories; CPython's `data`
    # extraction filter masks every mode to `& 0o755` and drops uid/gid, so a
    # verification that compared the EXTRACTED tree refused three entries of
    # an ordinary volume (measured: pack exit 0, verify exit 1). Without
    # these three the suite cannot see that, which is
    # [[fixture-stamps-what-the-product-does-not]] exactly.
    write(volume / "people" / "example" / "group.md", "group-writable\n", 0o664)
    write(volume / "shared" / "wide.md", "world-writable\n", 0o666)
    os.chmod(volume / "shared", 0o775)

    listing = nb.tree_listing(str(volume))
    write(inner / "listings" / "v4_memdata.sha256", listing)

    write(inner / "files" / "deploy" / ".env", "POSTGRES_PASSWORD=synthetic\n", 0o600)
    write(
        inner / "env" / "carried.env", "POSTGRES_PASSWORD=synthetic\nCORE_TOKEN=synthetic\n", 0o600
    )
    return stage


def plan(stage: pathlib.Path, *, passphrase=PASSPHRASE, base=None, entries_=None):
    """MANIFEST.json, written where `pack` looks for it."""
    payload = json.loads(json.dumps(base if base is not None else BASE))
    dump = stage / "inner" / "db" / "nova_core.dump"
    digest, size = nb.sha256_file(str(dump))
    payload["databases"][0]["dump_bytes"] = size
    payload["databases"][0]["dump_sha256"] = digest
    manifest = nb.build_manifest(
        payload,
        str(stage),
        entries() if entries_ is None else entries_,
        ["core", "gateway", "postgres"],
        passphrase=passphrase,
        reader_path=str(BACKUP_DIR / "nova_restore.py"),
    )
    (stage / "MANIFEST.json").write_text(nb.dump_manifest(manifest))
    return manifest


def run(argv, passphrase=PASSPHRASE):
    """novabundle.py's CLI, with the passphrase where the real one arrives:
    the first line of stdin, never argv and never an environment variable."""
    saved = sys.stdin
    sys.stdin = io.StringIO(passphrase + "\n")
    try:
        return nb.main(argv)
    finally:
        sys.stdin = saved


def make_bundle(root: pathlib.Path, *, passphrase=PASSPHRASE, out_name="nova-backup-test.tar"):
    stage = make_stage(root)
    manifest = plan(stage, passphrase=passphrase)
    out = root / (out_name + ".part")
    code = run(["pack", "--stage", str(stage), "--out", str(out)], passphrase)
    assert code == 0, f"pack exited {code}"
    final = root / out_name
    os.replace(out, final)
    return final, manifest, stage


def forge_bundle(root: pathlib.Path, mutate, *, passphrase=PASSPHRASE, name="forged.tar"):
    """A bundle whose MANIFEST never went through `load_manifest`.

    `pack` refuses a manifest this tool would not accept, which is the point
    — but the carried reader opens files it did not write, on a machine that
    has nothing, so it must refuse the same things independently. This builds
    what an attacker (or a future writer) could hand it.
    """
    stage = make_stage(root)
    manifest = plan(stage, passphrase=passphrase)
    mutate(manifest)
    (stage / "MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n")

    inner = stage / "inner.tgz"
    nb.build_inner_archive(str(stage), manifest, str(inner))
    payload = stage / "payload.enc"
    nb.encrypt_file(str(inner), str(payload), passphrase, manifest["encryption"]["chunk"])
    kat_blob = nb.encrypt_bytes(nb.KAT_PLAINTEXT, passphrase)
    kat_salt = bytes.fromhex(nb.parse_header(io.BytesIO(kat_blob))["salt"])
    digest, size = nb.sha256_file(str(payload))
    meta = nb.build_meta(
        manifest,
        payload_bytes=size,
        payload_sha256=digest,
        fingerprint=nb.key_fingerprint(passphrase, kat_salt),
        crypto_image="nova-core",
        fallback_image="python:3.12-slim",
        needs_images=["postgres:16", "python:3.12-slim"],
        chunk=manifest["encryption"]["chunk"],
    )
    work = stage / "outer"
    work.mkdir(exist_ok=True)
    staged = {}
    for member, blob in (
        ("README.txt", b"forged\n"),
        ("kat.sha256", (nb.sha256_bytes(nb.KAT_PLAINTEXT) + "\n").encode()),
        ("kat.enc", kat_blob),
        ("meta.json", (json.dumps(meta, indent=2) + "\n").encode()),
    ):
        (work / member).write_bytes(blob)
        staged[member] = str(work / member)
    staged["nova_restore.py"] = str(BACKUP_DIR / "nova_restore.py")
    staged["restore.sh"] = str(BACKUP_DIR / "restore.sh")
    staged["payload.enc"] = str(payload)
    out = root / name
    nb.build_outer_bundle(str(out), [(n, staged[n]) for n in nb.OUTER_ORDER], 0)
    return out, manifest, stage
