"""A synthetic stage, manifest and bundle, built the way `plan` and `pack`
build the real ones.

Everything here is invented: the passphrase is a test vector, the `.env` it
stages holds made-up values, and no path touches the operator's own tree. The
repo is public and a fixture that carried a real secret would be one commit
away from being one.
"""

import io
import json
import os
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

import novabundle as nb  # noqa: E402

HERE = pathlib.Path(__file__).resolve().parent
BACKUP_DIR = HERE.parent
FIXTURES = BACKUP_DIR / "fixtures"

# Synthetic. Not a passphrase anything real is sealed with.
PASSPHRASE = "aaaa-bbbb-cccc-dddd-eeee-ffff-gggg-hhhh"
OTHER_PASSPHRASE = "zzzz-yyyy-xxxx-wwww-vvvv-uuuu-tttt-ssss"

STAMP = "20260921T143002Z"

BASE = {
    "created_at": STAMP,
    "mode": "routine",
    "transport": "local",
    "source": {
        "host": "test-host",
        "os": "Linux 6.18.0-test",
        "repo_sha": "12ea01bf" + "0" * 32,
        "repo_dirty": False,
        "project": "nova",
        "compose_files": ["/repo/deploy/docker-compose.yml"],
        "profiles": ["inference"],
        "docker_version": "29.6.1",
        "compose_version": "v5.3.0",
        "pack_image_id": "sha256:" + "a" * 64,
    },
    "postgres": {
        "server_version": "16.10",
        "server_version_num": 160010,
        "pg_dump_version": "16.10",
        "pg_dump_major": 16,
        "container_image": "postgres:16",
        "container_image_id": "sha256:" + "b" * 64,
    },
    "session": {
        "TimeZone": "UTC",
        "DateStyle": "ISO, MDY",
        "IntervalStyle": "postgres",
        "extra_float_digits": "0",
        "bytea_output": "hex",
        "lc_numeric": "C",
    },
    "databases": [
        {
            "name": "nova_core",
            "owner": "core",
            "dump_member": "db/nova_core.dump",
            "dump_bytes": 0,
            "dump_sha256": "0" * 64,
            "counts_member": "db/nova_core.counts.tsv",
            "migrations_member": "db/nova_core.migrations.tsv",
            "tables": 2,
            "rows": 3,
            "selftest": {
                "scratch_db": "nova_selftest_a1b2c3d4",
                "tables_compared": 2,
                "equal": True,
            },
        }
    ],
    "identity": {
        "core_signing_key_sha256": "77d1" + "0" * 60,
        "tailnet_dns_name": None,
        "tailnet_state_carried": False,
        "device_count": 0,
        "people_count": 1,
    },
    "passphrase_source": "file",
    "excluded": [
        {
            "kind": "identity",
            "name": "core_signing_key",
            "disposition": "exclude-derived",
            "reason": "no device has ever paired on this hub, so there is no key to carry.",
        }
    ],
}


def entries():
    """What coverage() would hand `plan` for this synthetic stack."""
    return [
        nb.Entry(
            kind="volume",
            name="v4_memdata",
            disposition="include",
            reason="the notes",
            full_name="nova_v4_memdata",
            source="raw",
        ),
        nb.Entry(
            kind="volume",
            name="v4_ollama",
            disposition="exclude-redownload",
            reason="model weights, tens of GB, re-pulled on first use.",
            full_name="nova_v4_ollama",
            source="raw",
        ),
        nb.Entry(
            kind="bind",
            name="/repo/data",
            disposition="exclude-derived",
            reason="regenerated by detect_hardware on every install.",
            service="gateway",
            target="/data",
            source="config",
        ),
    ]


def write(path, text, mode=0o644):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    os.chmod(path, mode)


def make_stage(root: pathlib.Path) -> pathlib.Path:
    """The tree `backup.sh` would have staged by §9.1 step 13."""
    stage = root / "stage"
    inner = stage / "inner"
    (stage / "facts").mkdir(parents=True, exist_ok=True)

    write(inner / "db" / "nova_core.dump", "PGDMP" + "x" * 512)
    write(inner / "db" / "nova_core.counts.tsv", "public.people\t1\t42\npublic.turns\t2\t77\n")
    write(inner / "db" / "nova_core.migrations.tsv", "001_init.sql\t" + "c" * 64 + "\n")

    volume = inner / "volumes" / "v4_memdata"
    write(volume / "people" / "example" / "a-note.md", "a note\n")
    write(volume / "people" / "example" / "topics" / "a-topic.md", "another note\n")
    (volume / "empty-dir").mkdir(parents=True, exist_ok=True)
    link = volume / "people" / "current"
    if not link.exists():
        link.symlink_to("example")

    listing = nb.tree_listing(str(volume))
    write(inner / "listings" / "v4_memdata.sha256", listing)

    write(inner / "files" / "deploy" / ".env", "POSTGRES_PASSWORD=synthetic\n", 0o600)
    write(
        inner / "env" / "carried.env", "POSTGRES_PASSWORD=synthetic\nCORE_TOKEN=synthetic\n", 0o600
    )
    return stage


def plan(stage: pathlib.Path, *, passphrase=PASSPHRASE, base=None, entries_=None):
    """MANIFEST.json, written where `pack` looks for it."""
    payload = json.loads(json.dumps(base if base is not None else BASE))
    dump = stage / "inner" / "db" / "nova_core.dump"
    digest, size = nb.sha256_file(str(dump))
    payload["databases"][0]["dump_bytes"] = size
    payload["databases"][0]["dump_sha256"] = digest
    manifest = nb.build_manifest(
        payload,
        str(stage),
        entries() if entries_ is None else entries_,
        ["core", "gateway", "postgres"],
        passphrase=passphrase,
        reader_path=str(BACKUP_DIR / "nova_restore.py"),
    )
    (stage / "MANIFEST.json").write_text(nb.dump_manifest(manifest))
    return manifest


def run(argv, passphrase=PASSPHRASE):
    """novabundle.py's CLI, with the passphrase where the real one arrives:
    the first line of stdin, never argv and never an environment variable."""
    saved = sys.stdin
    sys.stdin = io.StringIO(passphrase + "\n")
    try:
        return nb.main(argv)
    finally:
        sys.stdin = saved


def make_bundle(root: pathlib.Path, *, passphrase=PASSPHRASE, out_name="nova-backup-test.tar"):
    stage = make_stage(root)
    manifest = plan(stage, passphrase=passphrase)
    out = root / (out_name + ".part")
    code = run(["pack", "--stage", str(stage), "--out", str(out)], passphrase)
    assert code == 0, f"pack exited {code}"
    final = root / out_name
    os.replace(out, final)
    return final, manifest, stage
