"""The census — §9.1 step 9, and §12.3's four properties.

The census SQL is GENERATED by `bk_census` in deploy/backup.sh, so this drives
the shipped shell with `bk_psql` replaced by a recorder, and asserts over the
statements it actually sent. Nothing here needs postgres: what is under test is
the statement, the session it is pinned in, and the algebra of the digest —
and the algebra is checked against a python model of `('x'||substr(md5(t::text),
1,16))::bit(64)::bigint`, not against a second copy of the SQL.

Why a sum and not `md5(string_agg(t::text, '' ORDER BY t::text))`: `string_agg`
materialises the whole table as one `text` value, and PostgreSQL's hard varlena
limit is 1 GB. Past it the query fails with `invalid memory alloc request size`,
which lands in the same branch as an un-castable type — so once any table
crosses roughly a gigabyte of text, EVERY backup refuses for ever and the only
remedy is a code change.
"""

import hashlib
import pathlib
import random
import subprocess

import pytest
from conftest import DEPLOY

from novabundle import SESSION_GUCS

BACKUP_SH = DEPLOY / "backup.sh"

# The six GUCs `t::text` renders timestamps, intervals, floats, bytea and
# numerics through. Every one of them is settable per-database and per-role, so
# a source pinning one set and a freshly initialised target pinning another
# produce different digests for identical data.
PINNED = {
    "TimeZone": "'UTC'",
    "DateStyle": "'ISO, MDY'",
    "IntervalStyle": "'postgres'",
    "extra_float_digits": "0",
    "bytea_output": "'hex'",
    "lc_numeric": "'C'",
}

DIGEST_SQL = "coalesce(sum(('x'||substr(md5(t::text),1,16))::bit(64)::bigint), 0)"


def run_sh(script: str, tmp_path: pathlib.Path, rows: str = "", tables: str = ""):
    """Source the real deploy/backup.sh with bk_psql replaced by a recorder.

    Returns (returncode, stdout, stderr, [statements sent]).
    """
    log = tmp_path / "sql.log"
    # The two canned answers go in through FILES, never through the harness
    # text: a table name carrying a quote is one of the cases here, and a
    # value spliced into a shell string could not carry it.
    (tmp_path / "tables").write_text(tables)
    (tmp_path / "rows").write_text(rows)
    harness = f"""
set -uo pipefail
. "{BACKUP_SH}"
bk_psql() {{
  printf '%s\\n' "$3" >> "{log}"
  case "$3" in
    *information_schema.tables*) cat "{tmp_path}/tables" ;;
    *"SET LOCAL"*) cat "{tmp_path}/rows" ;;
  esac
  return 0
}}
{script}
"""
    proc = subprocess.run(["bash", "-c", harness], capture_output=True, text=True, cwd=str(DEPLOY))
    sent = log.read_text().split("\n") if log.exists() else []
    return proc.returncode, proc.stdout, proc.stderr, sent


TWO_TABLES = "public\tpeople\npublic\tschema_migrations\n"
TWO_ROWS = "public.people\t0\t0\npublic.schema_migrations\t3\t99\n"


def census(tmp_path, rows=TWO_ROWS, tables=TWO_TABLES, db="nova_core"):
    return run_sh(f'bk_census cid "{db}"', tmp_path, rows=rows, tables=tables)


def measurement(sent):
    """The one statement that carries the measurement."""
    hits = [s for s in sent if "SET LOCAL" in s]
    assert len(hits) == 1, f"expected exactly one measurement statement, got {len(hits)}"
    return hits[0]


# ── the statement, and the session it is pinned in ──────────────────────────


def test_the_six_gucs_are_pinned_in_the_same_statement_as_the_measurement(tmp_path):
    rc, out, err, sent = census(tmp_path)
    assert rc == 0, err
    stmt = measurement(sent)
    for name, value in PINNED.items():
        assert f"SET LOCAL {name}={value};" in stmt, f"{name} is not pinned in the measurement"
    # ...and BEFORE the first measurement, not after it.
    assert stmt.index("SELECT '") > stmt.rindex("SET LOCAL ")


def test_the_pinned_set_is_exactly_the_one_the_manifest_records(tmp_path):
    """measurement-frames-outlive-their-code: a digest measured under a frame
    the manifest does not record cannot be compared at restore time, and a
    frame the manifest records but the census does not pin is a lie."""
    rc, out, err, sent = census(tmp_path)
    assert rc == 0, err
    assert set(PINNED) == set(SESSION_GUCS)
    _, session_json, _, _ = run_sh("bk_session_json", tmp_path)
    for name in SESSION_GUCS:
        assert f'"{name}"' in session_json, f"manifest.session does not record {name}"


def test_the_digest_is_the_constant_memory_sum_form(tmp_path):
    rc, out, err, sent = census(tmp_path)
    assert rc == 0, err
    stmt = measurement(sent)
    assert stmt.count(DIGEST_SQL) == 2, "every table is measured with the same sum expression"


def test_the_census_never_materialises_a_table_as_one_text_value(tmp_path):
    """The 1 GB varlena ceiling the sum form removes."""
    rc, out, err, sent = census(tmp_path)
    assert rc == 0, err
    for statement in sent:
        assert "string_agg" not in statement
        assert "array_agg" not in statement


def test_the_sum_is_never_cast_back_to_bigint(tmp_path):
    """sum(bigint) returns numeric, which cannot overflow. Casting it back
    would reintroduce the overflow the sum form exists to avoid."""
    rc, out, err, sent = census(tmp_path)
    assert rc == 0, err
    stmt = measurement(sent)
    assert "::bit(64)::bigint), 0)::" not in stmt
    assert "sum(" in stmt and "::numeric" not in stmt


def test_one_measurement_statement_per_catalogued_table(tmp_path):
    rc, out, err, sent = census(tmp_path)
    assert rc == 0, err
    assert measurement(sent).count("SELECT '") == 2


def test_the_catalogue_query_skips_system_schemas(tmp_path):
    rc, out, err, sent = census(tmp_path)
    assert rc == 0, err
    catalogue = [s for s in sent if "information_schema.tables" in s][0]
    assert "table_type = 'BASE TABLE'" in catalogue
    assert "table_schema NOT LIKE 'pg\\_%'" in catalogue
    assert "table_schema <> 'information_schema'" in catalogue


def test_identifiers_are_quoted_so_a_catalogue_name_cannot_escape(tmp_path):
    """The names come out of the catalogue, not out of this file, so they are
    quoted the only way that is safe for something nobody here wrote."""
    hostile = 'we"ird'
    tables = f"public\t{hostile}\npublic\tschema_migrations\n"
    rows = f"public.{hostile}\t1\t2\npublic.schema_migrations\t3\t99\n"
    rc, out, err, sent = census(tmp_path, rows=rows, tables=tables)
    assert rc == 0, err
    stmt = measurement(sent)
    assert 'FROM "public"."we""ird" AS t' in stmt


# ── what the census does with what comes back ───────────────────────────────


def test_an_empty_table_measures_as_zero_and_zero_rather_than_failing(tmp_path):
    """python-tool M2: the sum is NULL for an empty table and `psql -tAX`
    prints NULL as an empty string, indistinguishable from "no measurement" —
    so any zero-row table turned a healthy stack into a refused backup that
    sent the operator hunting a phantom."""
    rc, out, err, sent = census(tmp_path)
    assert rc == 0, err
    assert "public.people\t0\t0" in out
    assert DIGEST_SQL.startswith("coalesce("), "the NULL is coalesced in SQL, not in the shell"


def test_a_table_that_produced_no_digest_refuses_rather_than_being_dropped(tmp_path):
    rows = "public.people\t4\t\npublic.schema_migrations\t3\t99\n"
    rc, out, err, sent = census(tmp_path, rows=rows)
    assert rc != 0
    assert "cannot say it carried" in err
    assert out.strip() == "", "a refused census prints no partial measurement"


def test_a_missing_row_refuses_rather_than_being_a_shorter_census(tmp_path):
    rows = "public.schema_migrations\t3\t99\n"
    rc, out, err, sent = census(tmp_path, rows=rows)
    assert rc != 0
    assert "2 tables and the census produced 1" in err


def test_a_database_with_no_schema_migrations_refuses(tmp_path):
    tables = "public\tpeople\n"
    rc, out, err, sent = census(tmp_path, tables=tables, rows="public.people\t1\t2\n")
    assert rc != 0
    assert "schema_migrations" in err
    assert "so nothing can say which migrations" in err


def test_a_database_with_no_table_at_all_refuses(tmp_path):
    rc, out, err, sent = census(tmp_path, tables="", rows="")
    assert rc != 0
    assert "a reading that failed" in err


def test_the_output_is_lc_all_c_sorted(tmp_path):
    rows = "public.zeta\t1\t1\npublic.alpha\t2\t2\npublic.schema_migrations\t3\t3\n"
    tables = "public\tzeta\npublic\talpha\npublic\tschema_migrations\n"
    rc, out, err, sent = census(tmp_path, rows=rows, tables=tables)
    assert rc == 0, err
    names = [line.split("\t")[0] for line in out.splitlines()]
    assert names == sorted(names)


# ── the algebra of the digest, modelled rather than re-implemented ──────────


def pg_row_digest(text: str) -> int:
    """`('x'||substr(md5(t::text),1,16))::bit(64)::bigint` — the top 64 bits of
    the row's md5, reinterpreted as a SIGNED bigint."""
    value = int(hashlib.md5(text.encode()).hexdigest()[:16], 16)
    return value - (1 << 64) if value >= (1 << 63) else value


def pg_table_digest(rows) -> int:
    """`coalesce(sum(...), 0)` — sum(bigint) is numeric, so this is exact and
    unbounded, and an empty table is 0 rather than NULL."""
    return sum(pg_row_digest(r) for r in rows)


def test_the_digest_is_order_independent():
    rows = [f"({i},row {i},2026-09-21 00:00:00+00)" for i in range(500)]
    shuffled = rows[:]
    random.Random(41).shuffle(shuffled)
    assert shuffled != rows
    assert pg_table_digest(rows) == pg_table_digest(shuffled)


def test_the_digest_of_an_empty_table_is_zero():
    assert pg_table_digest([]) == 0


def test_a_single_changed_byte_changes_the_digest():
    assert pg_table_digest(["(1,a)"]) != pg_table_digest(["(1,b)"])


def test_two_million_rows_do_not_raise_or_overflow():
    """The ceiling the sum form removes. `sum(bigint)` returns numeric, so the
    worst case — two million rows all at -2^63 — is representable; a bigint
    accumulator would have overflowed at row 2."""
    rng = random.Random(7)
    total = 0
    for _ in range(2_000_000):
        total += rng.randrange(-(1 << 63), 1 << 63)
    assert isinstance(total, int)
    worst = -(1 << 63) * 2_000_000
    assert abs(worst) > (1 << 63), "the worst case really is outside bigint"


@pytest.mark.parametrize("value", ["", "x", "0" * 4096])
def test_the_row_digest_is_a_signed_64_bit_value(value):
    digest = pg_row_digest(value)
    assert -(1 << 63) <= digest < (1 << 63)
