#!/usr/bin/env bash
# Drive the e2e walk against a stack of its own.
#
#   tests/e2e/isolated.sh up      build + start the isolated stack, wait healthy
#   tests/e2e/isolated.sh walk    run the suite inside it (add playwright args)
#   tests/e2e/isolated.sh gpu     restart its ollama WITH the GPU (measurement)
#   tests/e2e/isolated.sh cpu     restart its ollama back on the CPU
#   tests/e2e/isolated.sh down    stop it and delete ITS volumes
#   tests/e2e/isolated.sh dc ...  any compose subcommand (project/file flags refused)
#
# WHY THIS SCRIPT EXISTS. The suite is destructive on purpose: it mints the
# instance's one and only owner, restarts every container, stops the gateway,
# and writes real files into the workspace volume. Doing that to the instance
# somebody actually uses is unrecoverable, and the only thing standing between
# the two is a `-p nova-e2e` on a five-line command. A flag you have to
# remember is not a control. This script is the control: every docker verb
# below goes through one array that already carries the project name and the
# overlay.
#
# That array alone is NOT the whole of it, and saying it was is this file's
# own first defect. Arguments given to `dc` are spliced in before the
# subcommand — exactly where docker compose reads its global flags — so
# `dc -p nova config` rendered `name: nova`, which made `dc -p nova down -v`
# one spelling away from a real instance's volumes. The `dc` arm now refuses
# -p/--project/-f/--file by shape. The other arms pass their arguments after
# the subcommand, where compose rejects a global flag itself (checked, rather
# than assumed: `up -p nova` dies with "unknown shorthand flag: 'p' in -p").
#
# The one thing it will not do for you: the two-model measurement needs the
# GPU, and `gpu` here does not check whether another stack's model is resident
# on the card. Ask ollama (/api/ps) and wait for an empty list — a resident
# model is something to wait for, never something to evict.
set -euo pipefail

PROJECT="nova-e2e"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_FILE="$SCRIPT_DIR/.isolated/.env"

# The stack, its isolation overlay, and the runner. Order matters: the
# isolated overlay must follow the base file (it resets what the base
# publishes), and the GPU overlay — when it is used at all — must follow the
# isolated one, which resets the reservation it puts back.
COMPOSE=(
  docker compose -p "$PROJECT"
  -f "$REPO_ROOT/deploy/docker-compose.yml"
  -f "$SCRIPT_DIR/docker-compose.isolated.yml"
)
RUNNER=(-f "$SCRIPT_DIR/docker-compose.e2e.yml")
GPU=(-f "$SCRIPT_DIR/docker-compose.isolated-gpu.yml")
SERVICES=(postgres core gateway memory web ollama)

# Secrets for a stack that exists to be thrown away, generated here rather
# than read from deploy/.env — the real instance's tokens are its own and have
# no business reaching a test stack. Written once and kept, so `up` after
# `down` (without -v) still matches the databases already on the volumes.
#
# NOVA_E2E_OWNER_PASSWORD is generated too, and that is a deliberate
# departure from the host-run rule that a person must choose it. The reason
# that rule exists is that on a real instance the first account is permanent,
# so a default in this repo would become a known credential on every machine
# that ran the suite. Here the account, the database and the volume it lives
# on are all created by this script and deleted by `down`, and the password
# never leaves this file — a fresh 32 hex characters per machine is strictly
# safer than anything a human would type twice.
ensure_env() {
  [ -f "$ENV_FILE" ] && return 0
  mkdir -p "$(dirname "$ENV_FILE")"
  umask 077
  {
    echo "# Generated by tests/e2e/isolated.sh — throwaway secrets for the"
    echo "# throwaway '$PROJECT' stack. Never deploy/.env; never committed."
    echo "POSTGRES_PASSWORD=$(openssl rand -hex 16)"
    echo "CORE_TOKEN=$(openssl rand -hex 32)"
    echo "CORE_GATEWAY_TOKEN=$(openssl rand -hex 32)"
    echo "CORE_MEMORY_TOKEN=$(openssl rand -hex 32)"
    echo "NOVA_E2E_OWNER_PASSWORD=$(openssl rand -hex 16)"
    echo "NOVA_E2E_UID=$(id -u)"
    echo "NOVA_E2E_GID=$(id -g)"
    echo "NOVA_E2E_DOCKER_GID=$(getent group docker | cut -d: -f3)"
  } > "$ENV_FILE"
  echo "generated $ENV_FILE"
}

# --env-file has to sit before the subcommand, so the array is assembled
# rather than appended to.
compose_run() {
  ensure_env
  local extra=()
  # Optional pre-subcommand overlays, e.g. the runner or the GPU file.
  while [ "${1:-}" = "--with" ]; do
    shift
    case "$1" in
      runner) extra+=("${RUNNER[@]}") ;;
      gpu) extra+=("${GPU[@]}") ;;
      *) echo "unknown overlay: $1" >&2; exit 2 ;;
    esac
    shift
  done
  "${COMPOSE[@]}" "${extra[@]}" --env-file "$ENV_FILE" --profile inference "$@"
}

case "${1:-}" in
  up)
    shift
    compose_run up -d --build "${SERVICES[@]}" "$@"
    echo
    echo "waiting for health…"
    deadline=$(( $(date +%s) + 600 ))
    while :; do
      table="$(compose_run ps --format '{{.Service}}={{.State}}/{{.Health}}' | sort | tr '\n' ' ')"
      # Every service in this stack declares a healthcheck, so "ready" is
      # literally "every line ends in /healthy" — a service reporting an
      # empty Health would fail this, which is the right answer for one that
      # somehow lost its check.
      unhealthy="$(printf '%s\n' "$table" | tr ' ' '\n' | grep -v '^$' | grep -v '/healthy$' || true)"
      if [ -z "$unhealthy" ]; then
        echo "healthy: $table"
        break
      fi
      if [ "$(date +%s)" -gt "$deadline" ]; then
        echo "NOT healthy within 600s: $table" >&2
        exit 1
      fi
      sleep 5
    done
    ;;
  walk)
    shift
    # `run` (not `up`) for the runner: it is a one-shot behind the e2e
    # profile, so it never becomes part of the stack it is testing.
    #
    # Any arguments are playwright's (a file list, --grep, --update-snapshots).
    # They cannot simply be appended: `compose run <service> <args>` REPLACES
    # the service's command, so `walk tests/07-tool-loop.spec.ts` would try to
    # execute the spec file as a binary. The command is rebuilt around them
    # instead, keeping the npm ci the image needs.
    compose_run --with runner --profile e2e run --rm e2e \
      sh -ec "npm ci --no-audit --no-fund && npx playwright test $*"
    ;;
  gpu)
    shift
    compose_run --with gpu up -d ollama "$@"
    ;;
  cpu)
    shift
    compose_run up -d ollama "$@"
    ;;
  down)
    shift
    # -v is scoped by the project name in COMPOSE above and reaches nothing
    # else: compose only ever removes volumes it declared for THIS project,
    # which are the nova-e2e_* ones it created.
    compose_run down -v "$@"
    ;;
  dc)
    shift
    # The only arm that takes arbitrary compose arguments, and therefore the
    # only one that has to be told what it may not say.
    #
    # compose_run splices these in BEFORE the subcommand, which is exactly
    # where docker compose reads its global flags — so a `-p` here beats the
    # `-p nova-e2e` in COMPOSE and every verb goes wherever it points.
    # Demonstrated before this guard existed, with `config` so nothing ran:
    # `isolated.sh dc -p nova config` rendered `name: nova`. That made
    # `dc -p nova down -v` a spelling away from deleting a real instance's
    # volumes, which falsified this file's own headline claim.
    #
    # The other arms pass their arguments AFTER the subcommand, where compose
    # refuses a global flag outright, so they need nothing.
    for arg in "$@"; do
      case "$arg" in
        -p|-p*|--project*|-f|-f*|--file*)
          echo "isolated.sh dc: refusing ${arg}." >&2
          echo "  The compose project and the compose files are what make this script safe" >&2
          echo "  to run beside a real instance, and this argument redefines one of them" >&2
          echo "  before the subcommand, where it wins. Edit the COMPOSE array above if you" >&2
          echo "  genuinely mean a different stack." >&2
          exit 2
          ;;
      esac
    done
    compose_run "$@"
    ;;
  *)
    sed -n '2,12p' "$0"
    exit 2
    ;;
esac
