"""Model-identity claims — she says which model she is, and it has to be true.

The incident, 2026-07-28: asked "what model are you running on right now?"
she answered "ollama:qwen2.5:3b" while every token was generated by
openrouter:anthropic/claude-haiku-4.5. The spending cap that had once made
that true was lifted hours earlier. She was reading four older messages —
two of them her OWN earlier wrong answers — and the prompt had carried the
correct model, in a recency-favoured block, with an explicit instruction to
trust it over memories. Clearing the conversation fixed it on the next turn,
which is what proves the transcript was the cause.

Sections, matching the sibling suites:
  1. MUST FLAG   — naming a model that is not the one generating the reply.
  2. MUST NOT    — honest namings, talk ABOUT other models, and the phrases
                   that merely look like claims. A false accusation here
                   contradicts Nova in front of the operator.
  3. DERIVED     — the check follows the live binding with no edit; change
                   the model and the same sentence flips verdict.
"""

import sys

sys.path.insert(0, "/app/backend")

from app import model_claims  # noqa: E402

LIVE = "openrouter:anthropic/claude-haiku-4.5"

FAILURES: list[str] = []


def check(label, cond, detail=""):
    print(f"  {'PASS' if cond else 'FAIL'}  {label}" + (f"   [{detail}]" if detail else ""))
    if not cond:
        FAILURES.append(label)


MUST_FLAG = [
    # the incident, verbatim and in the shapes around it
    "I'm running on ollama:qwen2.5:3b.",
    "I'm running on ollama:qwen2.5:3b (my primary model is unreachable).",
    "I am currently running on qwen3:8b.",
    "My model is gpt-4o.",
    "I'm powered by llama3.1:70b.",
    "I'm using ollama:qwen2.5:3b for this.",
    "This reply is generated by ollama:qwen2.5:3b.",
]

MUST_NOT_FLAG = [
    # every honest way of naming the live model
    "I'm running on openrouter:anthropic/claude-haiku-4.5.",
    "I'm running on anthropic/claude-haiku-4.5.",
    "I'm running on claude-haiku-4.5.",
    "I am currently running on Claude Haiku 4.5.",
    "My model is claude-haiku-4.5.",
    # talk ABOUT other models — recommending, comparing, describing an agent
    "qwen3:14b is a good local choice for coding.",
    "The coder agent runs on ollama:qwen3:14b.",
    "You could pull llama3.1:8b if you want something smaller.",
    "gpt-4o and claude-haiku-4.5 score similarly on that benchmark.",
    "Your compaction model is set to ollama:qwen2.5:3b.",
    # idioms that match the verb but name no model — the false positive that
    # would teach the operator to ignore the banner
    "I'm running on empty.",
    "I'm running on fumes.",
    "I am running late.",
    # nothing to say about it at all
    "The weather in Chicago is 71 degrees.",
    "",
]


def test_flagging():
    print("1. must flag — naming a model that is not the one answering")
    for text in MUST_FLAG:
        hit = model_claims.detect(text, LIVE)
        check(f"flags: {text[:56]}", hit is not None, str(hit))

    print("2. must NOT flag — honest namings, and talk about other models")
    for text in MUST_NOT_FLAG:
        hit = model_claims.detect(text, LIVE)
        check(f"quiet: {text[:56]}", hit is None, str(hit))


def test_bare_answers():
    """A reply that is nothing but an id — the incident's own shape, and the
    single most dangerous branch in the module.

    Shape alone is not evidence. `ollama:qwen3:14b` is the CORRECT whole answer
    to "which local model should I use for coding?", and this system has
    list_models and recommend_models as first-class tools, so that question is
    routine. Review found the first cut also firing on URLs, file:line
    references, container tags, clock times and ISO timestamps — every one of
    them a correct answer that would have had a correction stapled to it and
    read aloud. So the branch is gated on the operator asking about HER model.
    """
    print("5. bare answers — gated on the question being about her")
    asked = "What model are you running on right now?"
    not_asked = "Which local model should I use for coding?"

    check("the incident shape flags when she WAS asked",
          model_claims.detect("ollama:qwen2.5:3b.", LIVE,
                              asked_about_self=True) is not None)
    check("...and is silent when the question was about something else",
          model_claims.detect("ollama:qwen2.5:3b.", LIVE,
                              asked_about_self=False) is None)

    check("asks_about_own_model: 'what model are you running on right now?'",
          model_claims.asks_about_own_model(asked))
    check("...but NOT 'which local model should I use for coding?'",
          not model_claims.asks_about_own_model(not_asked))
    for q in ["What model is the ingestion role on?",
              "What's your compaction model set to?",
              "Which model should memory-curator use?",
              "list the models I have"]:
        check(f"...nor {q!r}", not model_claims.asks_about_own_model(q))
    for q in ["which model are you?", "what llm are you running on?",
              "what are you running on?"]:
        check(f"...but yes for {q!r}", model_claims.asks_about_own_model(q))

    # even with the gate open, these are not model ids
    print("6. …and with the gate OPEN, ordinary terse answers stay quiet")
    for t in ["3:30pm", "http://localhost:8000", "runner.py:1635",
              "ghcr.io/jeremyspofford/nova:v0.6.0", "2026-07-28T14:30:00Z",
              "app/migrations/050.sql", "127.0.0.1:5432"]:
        hit = model_claims.detect(t, LIVE, asked_about_self=True)
        # These CAN still flag on shape; what matters is that the gate keeps
        # them out of the real path, since none of them answers "what model
        # are you". Assert the gate, not the shape.
        check(f"gate keeps {t[:34]!r} out of the bare path",
              model_claims.detect(t, LIVE) is None, str(hit))


def test_resolved_model_is_ground_truth():
    """The comparison must be against what RAN, not what was configured.

    When a provider is unconfigured the runner swaps to a local model and the
    prompt tells her to say the SWAPPED name. Comparing against the binding
    then accuses her of lying at the exact moment she is telling the truth.
    """
    print("7. ground truth is the RESOLVED model, not the binding")
    binding, resolved = "openrouter:anthropic/claude-haiku-4.5", "ollama:qwen2.5:3b"
    truthful = "I'm running on qwen2.5:3b."
    check("truthful answer on a swapped turn is NOT flagged",
          model_claims.detect(truthful, resolved) is None,
          str(model_claims.detect(truthful, resolved)))
    check("...whereas comparing to the binding would have accused her",
          model_claims.detect(truthful, binding) is not None)
    check("and a genuinely wrong claim still flags on a swapped turn",
          model_claims.detect("I'm running on gpt-4o.", resolved) is not None)


def test_derived():
    print("3. DERIVED — the check follows the live binding, with no edit here")
    sentence = "I'm running on ollama:qwen2.5:3b."
    check("flagged while she is on the cloud model",
          model_claims.detect(sentence, LIVE) is not None)
    check("...and SILENT once that IS the live model",
          model_claims.detect(sentence, "ollama:qwen2.5:3b") is None,
          str(model_claims.detect(sentence, "ollama:qwen2.5:3b")))
    check("the reverse case flips too",
          model_claims.detect("I'm running on claude-haiku-4.5.",
                              "ollama:qwen2.5:3b") is not None)
    check("no ground truth = no accusation",
          model_claims.detect(sentence, "") is None)

    print("4. the correction names the real model")
    c = model_claims.correction(LIVE)
    check("carries the live model", LIVE in c, c)


def main() -> int:
    test_flagging()
    test_bare_answers()
    test_resolved_model_is_ground_truth()
    test_derived()
    if FAILURES:
        print(f"FAILED ({len(FAILURES)}): " + "; ".join(FAILURES[:6]))
        return 1
    print("all checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
