"""Distilled notes for the recall fixture, produced by the REAL distiller.

The same discipline as services/memory/tests/recall_vectors.py, and for the
same reason. That module records the embedding model's real vectors once and
replays them, because a hand-built vector space measures the arithmetic its
author put into it and nothing about quality. Notes are worse: a note I wrote
knowing the twenty questions measures ME. It would move the recall floor on a
number that flatters the slice.

So the fixture transcript goes through app/distil.py exactly as a real
conversation does — the same window, the same prompt, the same model, the same
citation check against a real database — and what the model produced is
committed. Reading it back costs no GPU and no network, and what is replayed
is a fact a model produced rather than a shape somebody chose.

    TEST_DATABASE_URL=... GATEWAY_URL=... CORE_GATEWAY_TOKEN=... \\
        MAKE_RECALL_DISTILLED=1 uv run pytest -q tests/recall_distilled.py -s

WHAT THIS IS NOT. It is not a measurement — it only produces the input to one.
Whether these notes raise answer-in-context is
services/memory/tests/test_recall_quality.py's question, and the honest answer
there might be "they do not".

WHERE THE OUTPUT GOES, and why it is a file rather than an import.
services/memory has no dependency on services/core and must not grow one: they
are separate processes, and memory's suite has to run on a checkout where core
is not installed. So this writes MARKDOWN into memory's own fixture directory
and memory's recall_corpus.py reads it the way it already reads the day files.
Producer and consumer share a directory, never a module.
"""

from __future__ import annotations

import os
import re
import uuid
from datetime import UTC, datetime, timedelta
from pathlib import Path

import pytest

from app import distil, identity
from app.main import app as core_app
from tests.conftest import requires_db

pytestmark = [
    requires_db,
    pytest.mark.skipif(
        os.environ.get("MAKE_RECALL_DISTILLED") != "1",
        reason="regenerates a committed fixture against a real model; set MAKE_RECALL_DISTILLED=1",
    ),
]

# memory's fixture corpus, by path. The one place the two services touch.
MEMORY_TESTS = Path(__file__).resolve().parents[3] / "services" / "memory" / "tests"
CORPUS_DIR = MEMORY_TESTS / "fixtures" / "recall_corpus"
OUT_DIR = CORPUS_DIR / "distilled"

# The fixture's own person and its day-offset scheme, mirrored from
# recall_corpus.py. Duplicated deliberately rather than imported: see above.
PERSON_ID = uuid.UUID("0f9b751c-b010-4a6b-8260-6a6255593a70")
BASELINE_TODAY = datetime(2026, 9, 9, tzinfo=UTC).date()

_SECTION = re.compile(r"^## (\d\d:\d\d)$", re.M)
_SLUG = re.compile(r"[^a-z0-9]+")


def _exchanges(text: str) -> list[tuple[str, str, str]]:
    """(HH:MM, user, assistant) for one fixture day — the inverse of what the
    journal writer produces, and the same parse recall_corpus._parse_day does."""
    parts = _SECTION.split(text)[1:]
    if not parts or len(parts) % 2:
        raise ValueError("fixture day has no '## HH:MM' sections")
    out = []
    for i in range(0, len(parts), 2):
        at, body = parts[i], parts[i + 1]
        user = body.split("User:", 1)[1].split("\n\nAssistant:")[0].strip()
        assistant = body.split("\n\nAssistant:", 1)[1].strip()
        out.append((at, user, assistant))
    return out


def _slug(text: str, limit: int = 60) -> str:
    return _SLUG.sub("-", text.lower()).strip("-")[:limit].strip("-") or "note"


async def _load_transcript(pool) -> dict[str, datetime]:
    """Write every fixture exchange into the database as real messages.

    Real rows, because the distiller's central honesty property is that a cited
    id resolves to a row of this person's inside the window it read. A fake in
    front of that check would be a fixture generated by something other than
    the thing being measured.

    Returns each day key -> the instant its last message was written, which is
    what a per-day pass uses as its window boundary.
    """
    await pool.execute(
        "INSERT INTO people (id, name, role) VALUES ($1, 'jeremy', 'owner') "
        "ON CONFLICT (id) DO NOTHING",
        PERSON_ID,
    )
    conversation = await pool.fetchval(
        "INSERT INTO conversations (person_id, title) VALUES ($1, 'recall fixture') RETURNING id",
        PERSON_ID,
    )
    ends: dict[str, datetime] = {}
    for path in sorted(CORPUS_DIR.glob("day-*.md")):
        key = path.stem
        day = BASELINE_TODAY - timedelta(days=int(key.split("-")[1]))
        last = None
        for at, user, assistant in _exchanges(path.read_text(encoding="utf-8")):
            hour, minute = (int(x) for x in at.split(":"))
            when = datetime(day.year, day.month, day.day, hour, minute, tzinfo=UTC)
            for role, content in (("user", user), ("assistant", assistant)):
                await pool.execute(
                    "INSERT INTO messages (conversation_id, role, content, created_at) "
                    "VALUES ($1, $2, $3, $4)",
                    conversation,
                    role,
                    content,
                    when,
                )
                when += timedelta(seconds=1)
            last = when
        ends[key] = last
    return ends


def _note(fact) -> str:
    """One distilled note in the store's own frontmatter shape, so memory can
    write it without knowing where it came from. `created` follows `said_at`,
    which is the property the whole note shape exists for."""
    said = fact.said_at.date().isoformat()
    lines = [
        "---",
        f"title: {fact.title}",
        "kind: topic",
        f"created: {said}",
        f"subject: {fact.subject}",
        f"said_at: {said}",
        "source:",
        f"  message_id: {fact.message_id}",
        f"  role: {fact.said_by}",
    ]
    if fact.live_source:
        lines += ["live_source:", f"  tool: {fact.live_source['tool']}"]
        args = fact.live_source.get("args") or {}
        if args:
            lines.append("  args:")
            lines += [f"    {k}: {v}" for k, v in args.items()]
    lines += ["---", "", fact.body, ""]
    return "\n".join(lines)


async def test_generate_the_distilled_notes(pool, monkeypatch):
    """Run the real distiller over the fixture transcript, one day at a time,
    and write what it produced into memory's fixture directory.

    ONE PASS PER DAY, oldest first — the shape a backfill walks, and the
    ordering matters for the same reason it matters there: superseding is
    last-write-wins by subject, so reading newest-first would leave the oldest
    statement of every restated fact as the live note.
    """
    # The real gateway. Whatever GATEWAY_URL/CORE_GATEWAY_TOKEN name, with no
    # transport override — the fakes are what conftest installs by default and
    # a fixture generated against one would measure the fake.
    core_app.state.peer_transports = {}

    ends = await _load_transcript(pool)
    person = identity.Person(id=PERSON_ID, name="jeremy", role="owner")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in OUT_DIR.glob("*.md"):
        stale.unlink()

    written = 0
    for key in sorted(ends, key=lambda k: -int(k.split("-")[1])):
        result = await distil.distil(
            core_app,
            pool,
            person,
            since=timedelta(hours=24),
            through=ends[key],
            subjects=(),
        )
        state = result.reason or f"read {result.read}, proposed {result.proposed}"
        print(f"{key}: {state} -> {len(result.facts)} facts")
        for index, fact in enumerate(result.facts):
            name = f"{key}-{index:02d}-{_slug(fact.title)}.md"
            (OUT_DIR / name).write_text(_note(fact), encoding="utf-8")
            written += 1

    print(f"\nwrote {written} distilled notes to {OUT_DIR}")
    assert written, (
        "the distiller produced nothing from the fixture transcript — that is a finding about "
        "the distiller, not a reason to hand-write the fixture"
    )
