"""Avatar asset kit — assemble viseme/blink webp assets from inpainted frames.

Phase 0 tooling for docs/plans/avatar-view.md (python/PIL toolchain — the
plan's avatar-kit.mjs, realized in the same venv that runs generation).

Inputs: a base work plate + full-frame variants generated by
avatar_gen.py (each variant differs from the ORIGINAL plate only inside
its known mask region — SD-inpaint composited through a feathered mask).

For each pick this script:
  1. verifies the alignment gate: zero changed pixels outside the
     variant's mask footprint (vs the original work plate);
  2. cuts the mask-bbox crop with the feathered mask baked into alpha —
     the renderer just drawImage()s it over the plate, no runtime masks;
  3. emits webp assets + manifest.json (crop origins in plate coords).

The chosen mouth-closed frame BECOMES the shipped plate (the raw concept
has parted lips); other crops composite over it. Blink composes freely
with any mouth crop because the regions are disjoint.

Setup:  uv venv env && uv pip install --python env/bin/python pillow numpy
Usage:  python avatar_kit.py --work <dir with base+candidates> \
            --out ../src/assets/avatar
Picks are pinned in PICKS below — edit and re-run to swap a frame.
"""
import argparse
import json
import os

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

# mask geometry — MUST match avatar_gen.py (plate coords, 848x842)
MOUTH_ELLIPSE = (374, 264, 506, 352)
EYE_ELLIPSES = [(340, 165, 416, 209), (444, 168, 520, 212)]
FEATHER = 10          # gaussian sigma used at generation time
PAD = 3 * FEATHER     # bbox margin covering the feather tail

# chosen candidates (2026-07-19 review + Jeremy's revision pass; sheets in
# mockups/avatar/). The numbered prefixes (round2/open3/closed2) mark
# prompt-iteration passes; avatar_gen.py now carries the final prompts, so
# a fresh regen emits equivalent content under the plain names.
PICKS = {
    "plate":       ("mouth-closed-s123.png", "mouth"),   # becomes the base
    "mouth-small": ("mouth-small-s77.png", "mouth"),
    "mouth-open":  ("mouth-open3-s111.png", "mouth"),    # Jeremy: no neon rim
    "mouth-round": ("mouth-round2-s99.png", "mouth"),
    "eyes-closed": ("eyes-closed2-s111.png", "eyes"),    # Jeremy: opaque lids
}


def build_mask(size, region):
    m = Image.new("L", size, 0)
    d = ImageDraw.Draw(m)
    boxes = [MOUTH_ELLIPSE] if region == "mouth" else EYE_ELLIPSES
    for b in boxes:
        d.ellipse(b, fill=255)
    return m.filter(ImageFilter.GaussianBlur(FEATHER))


def region_bbox(region, size):
    boxes = [MOUTH_ELLIPSE] if region == "mouth" else EYE_ELLIPSES
    x0 = max(0, min(b[0] for b in boxes) - PAD)
    y0 = max(0, min(b[1] for b in boxes) - PAD)
    x1 = min(size[0], max(b[2] for b in boxes) + PAD)
    y1 = min(size[1], max(b[3] for b in boxes) + PAD)
    return (x0, y0, x1, y1)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--work", required=True,
                    help="dir containing base-plate-work.png + candidates/")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    original = Image.open(f"{args.work}/base-plate-work.png").convert("RGB")
    orig_arr = np.asarray(original, dtype=np.int16)
    os.makedirs(args.out, exist_ok=True)

    # ── alignment gate: variants may differ from the ORIGINAL plate only
    #    inside their own mask footprint ─────────────────────────────────
    failures = []
    frames = {}
    for name, (fname, region) in PICKS.items():
        frame = Image.open(f"{args.work}/candidates/{fname}").convert("RGB")
        if frame.size != original.size:
            failures.append(f"{name}: size {frame.size} != {original.size}")
            continue
        mask = np.asarray(build_mask(original.size, region))
        diff = np.abs(np.asarray(frame, dtype=np.int16) - orig_arr).max(axis=2)
        stray = int(np.count_nonzero(diff[mask == 0]))
        print(f"gate {name:12s} stray-pixels-outside-mask: {stray}")
        if stray:
            failures.append(f"{name}: {stray} stray pixels")
        frames[name] = frame
    if failures:
        raise SystemExit("ALIGNMENT GATE FAILED: " + "; ".join(failures))

    # ── emit plate (the closed-mouth frame) ────────────────────────────
    plate = frames["plate"]
    plate.save(f"{args.out}/plate.webp", quality=90, method=6)

    # ── emit crops with feathered mask baked into alpha ────────────────
    manifest = {
        "plate": {"file": "plate.webp",
                  "width": plate.width, "height": plate.height},
        "regions": {},
    }
    for name, (fname, region) in PICKS.items():
        if name == "plate":
            continue
        bbox = region_bbox(region, original.size)
        mask = build_mask(original.size, region)
        crop = frames[name].crop(bbox).convert("RGBA")
        crop.putalpha(mask.crop(bbox))
        crop.save(f"{args.out}/{name}.webp", lossless=True, method=6)
        manifest["regions"][name] = {
            "file": f"{name}.webp", "x": bbox[0], "y": bbox[1],
            "w": bbox[2] - bbox[0], "h": bbox[3] - bbox[1],
        }

    with open(f"{args.out}/manifest.json", "w") as f:
        json.dump(manifest, f, indent=2)
    total = sum(os.path.getsize(f"{args.out}/{f}") for f in os.listdir(args.out))
    print(f"kit written to {args.out} — {total//1024} KB total")


if __name__ == "__main__":
    main()
