"""Claiming to be a model she is not.

Third sibling of narration.py and capability_claims.py, and the same design.
Narration catches ANNOUNCING work that never ran. capability_claims catches
CLAIMING AN ABILITY no granted tool provides. This catches STATING THE WRONG
MODEL — "I'm running on ollama:qwen2.5:3b" said on 2026-07-28 while every
token of that very sentence was generated by openrouter:anthropic/claude-
haiku-4.5.

What makes this one worth a check of its own is that it FEEDS ITSELF. The
prompt already carried the truth: a `## Model (live)` block, resolved fresh
each turn, naming the real model and saying in as many words "trust this
block over memories, and never claim you can't check". She read four older
messages instead — two of them her own earlier wrong answers — and repeated
them. Every wrong answer becomes the history that produces the next one, so
the error does not decay; it compounds. Clearing the conversation fixed it
instantly, which is the proof: the model was never the problem, the
transcript was.

That is precisely why the correction is written into the reply TEXT rather
than only raised as a banner. A banner persists as a role='tool' row and the
chat history loader keeps only user/assistant rows, so the false claim would
be replayed forever and the correction never would. Appending to the answer
is the only form of this check that breaks the loop.

DERIVED, NEVER HARDCODED. There is no list of model names here. The only
ground truth is the model string the runner actually used this turn, passed
in; a claim matches or it does not. Swap the binding in Settings -> Agents
and this check follows it with no edit.

Precision is the design, as in both siblings: this contradicts Nova in front
of the operator, and one false accusation costs more than several missed
catches. Talking ABOUT other models, recommending them, comparing them, and
answering questions about what a model can do all stay unflagged — only a
first-person claim about what is generating THIS reply is even considered.
"""

from __future__ import annotations

import re
from typing import Optional

# A first-person statement about what is running this turn, capturing the
# model that follows. Deliberately narrow: the verb has to be about running
# or being powered by something, and the subject has to be her.
#
# "The coder agent runs on qwen3" is a statement about an agent and is not
# matched — the dispatch index already states each specialist's binding, and
# flagging her for describing one correctly would be the worst outcome here.
_CLAIM = re.compile(
    r"\b(?:"
    r"i(?:'m|’m| am)?\s+(?:currently\s+)?(?:running|answering|operating)"
    r"(?:\s+(?:on|with))?"
    r"|i(?:'m|’m| am)\s+(?:currently\s+)?(?:on|using|powered by)"
    r"|my\s+(?:current\s+)?model\s+is"
    r"|(?:this|the)\s+(?:turn|reply|response)\s+(?:is\s+)?"
    r"(?:running|generated)\s+(?:on|by)"
    r")\s+"
    r"[\"'`*]{0,2}"                       # markdown/quote noise before the id
    r"([A-Za-z0-9][A-Za-z0-9._:/+-]{2,})",
    re.IGNORECASE)

# A token only counts as a MODEL REFERENCE if it looks like one. Without this,
# "I'm running on fumes" and "I am running on empty" are model claims that
# match nothing and get flagged — the exact false positive that teaches an
# operator to ignore the banner. Model ids in this system always carry a
# digit, a slash or a colon (openrouter:anthropic/claude-haiku-4.5,
# ollama:qwen2.5:3b, gpt-4, llama3).
_LOOKS_LIKE_MODEL = re.compile(r"[0-9]|[:/]")

# The BARE answer: a reply that is nothing but a model id. Not an edge case —
# it is the shape the prompt asks for ("answer with just the model name, then
# stop") and it is what she actually said on 2026-07-28: the entire reply was
# "ollama:qwen2.5:3b.". Without it the check misses the incident it exists for.
#
# But shape alone is nowhere near enough, and a first pass that trusted it was
# badly wrong. `ollama:qwen3:14b` is also the correct whole answer to "which
# local model should I use for coding?" — and this system has list_models and
# recommend_models as first-class tools, so that question is routine. Review
# found the same pattern firing on `http://localhost:8000`, `runner.py:1635`,
# `ghcr.io/jeremyspofford/nova:v0.6.0`, `3:30pm` and `2026-07-28T14:30:00Z`.
# Every one of those would have had a correction appended to a correct answer,
# and read aloud on a voice turn.
#
# So the bare path is gated on the OPERATOR having asked about HER model. That
# is the only context in which a bare model id is a claim about herself rather
# than a fact about something else.
_BARE = re.compile(r"^(?=[^\s]*[A-Za-z])(?=[^\s]*[0-9])[A-Za-z0-9][A-Za-z0-9._:/+-]*[:/][A-Za-z0-9._:/+-]*$")

# "what model are you running on" — second person, about a model. Deliberately
# NOT matched: "which local model should I use", "what model is the ingestion
# role on", "what's your compaction model" — all questions about a model that
# is not the one answering, and all of which a bare id correctly answers.
_SELF_MODEL_QUESTION = re.compile(
    r"\b(?:what|which|who)\b[^?]{0,60}\b(?:model|llm)\b[^?]{0,40}\bare\s+you\b"
    r"|\b(?:what|which)\s+(?:model|llm)\s+are\s+you\b"
    r"|\bwhat\s+are\s+you\s+running\s+on\b"
    r"|\byour\s+(?:current\s+)?(?:model|llm)\b(?!\s+(?:for|is\s+set))",
    re.IGNORECASE)


def asks_about_own_model(user_text: str) -> bool:
    """Did the operator ask which model SHE is? Gates the bare-answer path."""
    return bool(user_text and _SELF_MODEL_QUESTION.search(user_text))

_ALNUM = re.compile(r"[^a-z0-9]+")


def _squash(s: str) -> str:
    """`openrouter:anthropic/claude-haiku-4.5` -> `openrouteranthropicclaudehaiku45`.

    Comparing squashed forms is what lets every HONEST way of naming the live
    model pass: the full id, the provider-less form, the bare family name, and
    the prose form all reduce to a substring of it. "Claude Haiku 4.5",
    "anthropic/claude-haiku-4.5" and "claude-haiku-4.5" are the same answer.
    """
    return _ALNUM.sub("", s.lower())


def detect(final_text: str, live_model: str,
           asked_about_self: bool = False) -> Optional[str]:
    """The wrongly-claimed model when the text says it is running on something
    other than `live_model`; None otherwise.

    `live_model` MUST be the model that actually generated the turn — the
    RESOLVED one, after any provider swap or mid-turn fallback, not the agent's
    configured binding. Pass the binding and this check accuses her of lying
    every time a swap makes her tell the truth.

    `asked_about_self` opens the bare-answer path, and defaults to False so a
    caller that cannot tell simply gets the conservative behaviour.
    """
    if not final_text or not live_model:
        return None
    truth = _squash(live_model)
    if not truth:
        return None
    bare = final_text.strip().strip(".,;:!?\"'`*")
    if asked_about_self and _BARE.match(bare):
        squashed = _squash(bare)
        if squashed and squashed not in truth and truth not in squashed:
            return bare
        return None
    for m in _CLAIM.finditer(final_text):
        claimed = m.group(1).strip().strip(".,;:!?\"'`*")
        if not claimed or not _LOOKS_LIKE_MODEL.search(claimed):
            continue
        squashed = _squash(claimed)
        if not squashed:
            continue
        # Either direction counts as honest: she may name more of the id than
        # the live string carries, or less of it.
        if squashed in truth or truth in squashed:
            continue
        return claimed
    return None


def correction(live_model: str) -> str:
    """The sentence appended to a reply that named the wrong model.

    Written into the answer, not a banner, so the next turn reads the
    correction alongside the claim instead of the claim alone.
    """
    return (f"\n\n[Correction: this turn was generated by {live_model}. "
            f"Any model named above is wrong — earlier notes in this "
            f"conversation describe the turn they were written on.]")
