"""Generate tests/fixtures/envelope_vectors.json — ONCE, on purpose.

The fixture is the contract between services/core/app/envelopes.py and
apps/novad's internal/wire: both suites assert the SAME committed bytes, so a
canonicalization or signing drift on either side turns both red instead of one
machine silently refusing every command the other signs.

That only works if the file is asserted, never regenerated by the test run. So
this is a helper you invoke by hand and commit the output of:

    cd services/core && uv run python tests/fixtures/gen_envelope_vectors.py

If a test goes red against this file, the question is which implementation
moved — re-running this script to make the test green again would delete the
only evidence that anything changed.

The key is a FIXED seed (never used for anything real; core's actual signing
key is generated per-install and lives in the core_signing_key table). The
seed is the ASCII of a phrase so it is legible in both the JSON and a Go test:

    "novad-slice-05-envelope-vectors!"  — exactly 32 bytes, an ed25519 seed.

The five vectors cover what actually breaks cross-language JSON:
  1. empty args — the baseline shape, and the case a Go `map[string]any`
     round-trips to `null` if the daemon is careless;
  2. non-ASCII AND angle-bracket/ampersand text — python escapes the former
     and not the latter, Go's encoding/json does exactly the opposite by
     default;
  3. a payload whose keys are written scrambled — its committed canonical
     bytes are in sorted order, which is what proves canonicalization ran;
  4. a revoked-proof body (S42a) — the shape devices_ws.py signs into a
     revoked auth_error and apps/novad's wire.VerifyRevokedProof checks. Not
     a command envelope: no capability, no args, a different key set
     (kind/v/device_id/nonce) — proving the SAME canonicalizer and the SAME
     seed sign this shape identically on both sides too, not only the
     envelope shape the first three vectors cover;
  5. a Windows path — backslashes and a drive colon (S42a Task 13), as
     device_list_files sends in a `fs.list` envelope's args once the path
     check accepts a device's own OS. Every backslash must be escaped as
     `\\` by BOTH encoders; nothing else here exercises that byte.

issued_at/expires_at are frozen literals rather than time.time(): a vector
that changes every run pins nothing.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric import ed25519

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from app import envelopes  # noqa: E402  (after the path insert, deliberately)

SEED_PHRASE = b"novad-slice-05-envelope-vectors!"
OUT = Path(__file__).resolve().parent / "envelope_vectors.json"

# Fixed so the vectors are reproducible; both are inside the plausible range a
# real envelope carries, and vector 2's expiry is deliberately a different TTL
# so nothing can pass by assuming 60.
ISSUED_AT = 1756600000
EXPIRES_AT = ISSUED_AT + 60

PAYLOADS = [
    {
        "note": "empty args — the baseline envelope shape",
        "payload": {
            "v": 1,
            "envelope_id": "0f7f4b3e-2c1a-4a5d-9b6e-1d2c3b4a5f60",
            "device_id": "11111111-2222-3333-4444-555555555555",
            "capability": "system.info",
            "args": {},
            "issued_at": ISSUED_AT,
            "expires_at": EXPIRES_AT,
        },
    },
    {
        "note": (
            "nested + non-ASCII + <>& — python escapes non-ASCII and leaves "
            "angle brackets alone; Go's encoding/json does the opposite by "
            "default. The daemon matches THESE bytes."
        ),
        "payload": {
            "v": 1,
            "envelope_id": "8a2d6c11-9e77-4b0f-8c3a-6de5f0a1b2c3",
            "device_id": "11111111-2222-3333-4444-555555555555",
            "capability": "fs.list",
            "args": {
                "path": "/home/jeremy/notes/café",
                "opts": {"limit": 10, "recursive": False, "since": None},
                "tags": ["naïve", "a<b>c&d", "✓"],
            },
            "issued_at": ISSUED_AT,
            "expires_at": ISSUED_AT + 120,
        },
    },
    {
        "note": (
            "keys written scrambled — the committed canonical bytes are in "
            "sorted order, which is the proof canonicalization happened"
        ),
        "payload": {
            "issued_at": ISSUED_AT,
            "capability": "shell.exec",
            "v": 1,
            "expires_at": EXPIRES_AT,
            "args": {"timeout_s": 30, "argv": ["echo", "hello"], "cwd": "/tmp"},
            "device_id": "11111111-2222-3333-4444-555555555555",
            "envelope_id": "c4b3a2d1-5566-4778-99aa-bbccddeeff00",
        },
    },
    {
        "note": (
            "the revoked-proof body (S42a) — devices_ws.py signs this into a "
            "revoked auth_error's `proof`, and apps/novad's "
            "wire.VerifyRevokedProof checks it against the pinned core key. "
            "No capability, no args: a different shape than a command "
            "envelope, canonicalized and signed the same way."
        ),
        "payload": {
            "kind": "revoked",
            "v": 1,
            "device_id": "11111111-2222-3333-4444-555555555555",
            "nonce": "0123456789abcdef" * 4,
        },
    },
    {
        "note": (
            "a Windows path — backslashes and a drive colon, as device_list_files "
            "sends on Windows (S42a); the JSON escapes each backslash, and both "
            "encoders must agree on those bytes"
        ),
        "payload": {
            "v": 1,
            "envelope_id": "5e8a1f0c-7d42-4c1e-9a3b-2f6d8c0e4b71",
            "device_id": "11111111-2222-3333-4444-555555555555",
            "capability": "fs.list",
            "args": {"path": "C:\\Users\\owner\\Desktop"},
            "issued_at": ISSUED_AT,
            "expires_at": EXPIRES_AT,
        },
    },
]


def main() -> None:
    if len(SEED_PHRASE) != 32:
        raise SystemExit(f"seed must be 32 bytes, got {len(SEED_PHRASE)}")
    key = ed25519.Ed25519PrivateKey.from_private_bytes(SEED_PHRASE)
    document = {
        "_comment": (
            "Generated by tests/fixtures/gen_envelope_vectors.py. Asserted by "
            "services/core/tests/test_envelopes.py AND apps/novad's Go suite. "
            "Do not regenerate to make a test pass — find out which side moved."
        ),
        "seed_hex": SEED_PHRASE.hex(),
        "public_key_hex": key.public_key().public_bytes_raw().hex(),
        "vectors": [
            {
                "note": entry["note"],
                "payload": entry["payload"],
                "canonical": envelopes.canonical(entry["payload"]).decode("utf-8"),
                "sig_hex": envelopes.sign(key, entry["payload"]),
            }
            for entry in PAYLOADS
        ],
    }
    OUT.write_text(json.dumps(document, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(document['vectors'])} vectors)")


if __name__ == "__main__":
    main()
